apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: $PROJECT_NAME
  name: devops-go-sample
  labels:
    app: devops-go-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-go-sample
  template:
    metadata:
      labels:
        app: devops-go-sample
    spec:
      containers:
      - name: go
        image: $REGISTRY/$DOCKERHUB_USERNAME/$APP_NAME_FULL
        imagePullPolicy: Always

---

kind: Service
apiVersion: v1
metadata:
  labels:
    app: devops-go-sample-service-svc
  name: devops-go-sample-service-svc
  namespace: $PROJECT_NAME
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31702
  selector:
    app: devops-go-sample
